<?php
return array (
  'hot_city' => 
  array (
    'fieldid' => '402',
    'modelid' => '27',
    'siteid' => '1',
    'field' => 'hot_city',
    'name' => '热门城市',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u592a\\u539f|141","boxtype":"radio","fieldtype":"varchar","minnumber":"1","cols":"5","width":"80","size":"1","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '太原|141',
    'boxtype' => 'radio',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
);
?>