<?php
return array (
  9 => 
  array (
    'id' => '9',
    'catid' => '11',
    'typeid' => '62',
    'title' => '肠胃炎夏季高发预防记住这几点肠胃炎夏季高发预防记住这',
    'style' => '',
    'thumb' => '',
    'keywords' => '2222adadadadaddada',
    'description' => '春夏交替5条原则养好肠胃111',
    'posids' => '1',
    'url' => 'http://cmstest.duyiwang.cn/index.php?m=content&c=index&a=show&catid=11&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1496282650',
    'updatetime' => '1496369987',
    'hitsid' => 'c-1-9',
    'views' => '19',
    'yesterdayviews' => '13',
    'dayviews' => '6',
    'weekviews' => '19',
    'monthviews' => '19',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '11',
    'typeid' => '67',
    'title' => '如果有一天，你发现父母喜欢看医疗广告了……',
    'style' => '',
    'thumb' => 'http://cmstest.duyiwang.cn/uploadfile/2017/0601/20170601042233263.png',
    'keywords' => '父母 医疗 广告',
    'description' => '健骨养生',
    'posids' => '1',
    'url' => 'http://cmstest.duyiwang.cn/index.php?m=content&c=index&a=show&catid=11&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'yunyin1',
    'inputtime' => '1496305073',
    'updatetime' => '1496370945',
    'hitsid' => 'c-1-10',
    'views' => '18',
    'yesterdayviews' => '8',
    'dayviews' => '10',
    'weekviews' => '18',
    'monthviews' => '18',
  ),
);
?>