<?php
return array (
  4 => 
  array (
    'catid' => '4',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '2',
    'arrparentid' => '0,1,2',
    'child' => '0',
    'arrchildid' => '4',
    'catname' => '用药指导老师',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'yuyuetiyan/yishi/',
    'catdir' => 'zhidaolaoshi',
    'url' => 'http://localhost/php_cms/index.php?m=content&c=index&a=lists&catid=4',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_dietitian","list_template":"list_dietitian","show_template":"show_dietitian","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '4',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yongyaozhidaolaoshi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  7 => 
  array (
    'catid' => '7',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '7',
    'catname' => '公司介绍',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'about_us',
    'url' => 'http://localhost/php_cms/index.php?m=content&c=index&a=lists&catid=7',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '7',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'gongsijieshao',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
);
?>