<?php
return array (
  1 => 
  array (
    'catid' => '1',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '1,2,3,4',
    'catname' => '预约体验',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'yuyuetiyan',
    'url' => 'http://localhost/php_cms/index.php?m=content&c=index&a=lists&catid=1',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '1',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yuyuetiyan',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  2 => 
  array (
    'catid' => '2',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '1',
    'arrparentid' => '0,1',
    'child' => '1',
    'arrchildid' => '2,3,4',
    'catname' => '医师',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'yuyuetiyan/',
    'catdir' => 'yishi',
    'url' => 'http://localhost/php_cms/index.php?m=content&c=index&a=lists&catid=2',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_dietitian","list_template":"list_dietitian","show_template":"show_dietitian","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '2',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yishi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  3 => 
  array (
    'catid' => '3',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '2',
    'arrparentid' => '0,1,2',
    'child' => '0',
    'arrchildid' => '3',
    'catname' => '营养师',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'yuyuetiyan/yishi/',
    'catdir' => 'yingyangshi',
    'url' => 'http://localhost/php_cms/index.php?m=content&c=index&a=lists&catid=3',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_dietitian","list_template":"list_dietitian","show_template":"show_dietitian","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '3',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingyangshi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  4 => 
  array (
    'catid' => '4',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '2',
    'arrparentid' => '0,1,2',
    'child' => '0',
    'arrchildid' => '4',
    'catname' => '用药指导老师',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'yuyuetiyan/yishi/',
    'catdir' => 'zhidaolaoshi',
    'url' => 'http://localhost/php_cms/index.php?m=content&c=index&a=lists&catid=4',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_dietitian","list_template":"list_dietitian","show_template":"show_dietitian","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '4',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yongyaozhidaolaoshi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>